add_newline = true
format = "[](#ffd6a5)$username[](bg:#fdffb6 fg:#ffd6a5)$directory[](bg:#caffbf fg:#fdffb6)$git_branch$git_status[](bg:#9bf6ff fg:#caffbf)$docker_context[](bg:#a0c4ff fg:#9bf6ff)$nix_shell[](bg:#bdb2ff fg:#a0c4ff)[](fg:#bdb2ff)$line_break$character"
scan_timeout = 10

[cmd_duration]
disabled = true

[directory]
format = "[ $path ]($style)"
style = "fg:#101116 bg:#fdffb6"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = " "
Downloads = " "
Music = " "
Pictures = " "

[docker_context]
format = "[ $symbol $context ]($style)"
style = "fg:#101116 bg:#9bf6ff"
symbol = " "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:#101116 bg:#caffbf"
symbol = ""

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "fg:#101116 bg:#caffbf"

[nix_shell]
format = "[ $symbol $state: $name ]($style)"
style = "fg:#101116 bg:#da6270"
symbol = "❄️ "

[username]
disabled = false
format = "[$user ]($style)"
show_always = true
style_root = "fg:#101116 bg:#ffd6a5"
style_user = "fg:#101116 bg:#ffd6a5"
