#theme = "catppuccin_latte"
theme = "catppuccin_mocha"

[editor]
auto-completion = false
auto-pairs = false
bufferline = "multiple"
color-modes = true
continue-comments = false
mouse = false
text-width = 120

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true
display-signature-help-docs = true

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["primary-selection-length"]

[editor.whitespace]
render = "all"

[keys.insert]
C-k = "completion"

[keys.normal]
c = "change_selection_noyank"
d = "delete_selection_noyank"
C-k = "signature_help"
