# colorscheme
colorscheme palenight
#colorscheme base16_monokai

# Use plug.kak to manage plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# add tab commands
plug "andreyorst/smarttab.kak"

# kakboard yanks to clipboard
plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

# language server
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
}

# run the language server for the following languages
hook global WinSetOption filetype=(rust|python|go|c|cpp|latex) %{
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor true
    lsp-auto-hover-enable
    lsp-enable-window
}

# Format commands
hook global WinSetOption filetype=rust %{
	set window formatcmd 'rustfmt'
}

hook global WinSetOption filetype=go %{
    set window formatcmd 'gofmt'
}

# Format on save
hook global WinSetOption filetype=(rust|go) %{
    hook global BufWritePre .* %{ format }
}

# Tab options
hook global WinSetOption filetype=rust expandtab
hook global WinSetOption filetype=go smarttab

# No clippy
set-option global ui_options ncurses_assistant=none

# tab width
set-option global tabstop 4
set-option global indentwidth 4

# Line numbers
add-highlighter global/ number-lines
