# colorscheme
colorscheme palenight
#colorscheme base16_monokai

# Use plug.kak to manage plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# add tab commands
plug "andreyorst/smarttab.kak"

# kakboard yanks to clipboard
plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

# language server
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}

# run the language server for the following languages
hook global WinSetOption filetype=(c|cpp|go|latex|python|rust) %{
    set-option window lsp_auto_highlight_references true
    set-option window lsp_hover_anchor true
    lsp-auto-hover-enable
    lsp-enable-window
}

# Format commands
hook global WinSetOption filetype=rust %{
	set window formatcmd 'rustfmt'
}

hook global WinSetOption filetype=go %{
    set window formatcmd 'gofmt'
}

hook global WinSetOption filetype=(c|cpp) %{
    set window formatcmd 'clang-format --style=file'
}

# Format on save
hook global WinSetOption filetype=(cpp|go|rust) %{
    hook global BufWritePre .* %{ format }
}

# Git gutter
hook global WinSetOption filetype=(c|cpp|go|python|rust) %{
    hook global BufWritePost .* %{ git show-diff }
    hook global BufReload .* %{ git show-diff }
    hook global WinDisplay .* %{ git show-diff }
}

# Tab options
hook global WinSetOption filetype=(cpp|rust) expandtab
hook global WinSetOption filetype=go smarttab

# No clippy
set-option global ui_options ncurses_assistant=none

# tab width
set-option global tabstop 4
set-option global indentwidth 4

hook global WinSetOption filetype=(c|cpp) %{
    set-option global tabstop 2
    set-option global indentwidth 2
}

# Line numbers
add-highlighter global/ number-lines

# Wrap text without modifying the buffer
add-highlighter global/ wrap

# Highlight matching characters
add-highlighter global/ show-matching
